### ISSUE TITLE
Use of XML Roberta issue

### ISSUE THREAD

**Issue by saharghannay** [LightChen233/GL-CLeF#2]
I am trying to use your tool for my research, and I would like to use XML Roberta instead of Bert
So I used XMLRobertaFast as a tokenizer (tokenizer=XLMRobertaTokenizerFast.from_pretrained('xlm-roberta-large’))
And changed in the base_model and contrastive_learning the xlm-robera-large instead of 'bert-base-multilingual-uncased

However I had this assertion error. 

 self.train_features = self.train_sampler.convert_examples_to_features()
  File "GL-CLeF/utils/preprocess/Sampler.py", line 72, in convert_examples_to_features
    original=self.convert_tokens_to_ids_with_padding(example.words,example.labels)
  File "GL-CLeF/utils/preprocess/Sampler.py", line 147, in convert_tokens_to_ids_with_padding
    segment_ids) == self.max_seq_length and len(label_ids) == self.max_seq_length
AssertionError

Could you help me please to solve this error.

**Comment by qinlibo-hit** [comment]
Hi Sarhar @saharghannay ,

Thanks for your interest in our work.

Since our code is based on BERT, you can modify '''input_ids.extend(self.tokenizer.convert_tokens_to_ids(self.tokenizer.tokenize('[CLS]')))''' on line 119 to '''input_ids.append(self.tokenizer.cls_token_id)''' to match the code for XLM.
Hope it is useful for you.

**Comment by saharghannay** [comment]
Hi,

Thank you,

I will try that. 


Best
------------------------
Sahar Ghannay
https://saharghannay.github.io
 <https://saharghannay.github.io/>https://cv.archives-ouvertes.fr/sahar-ghannay <https://cv.archives-ouvertes.fr/sahar-ghannay>
Associate Professor at Université Paris-Saclay, CNRS, Laboratoire Interdisciplinaire des Sciences du Numérique, 91400, Orsay, France 

—> January 1, 2021. Inauguration of LISN, the interdisiplinary computer science laboratory uniting 14 research groups, 7 from LIMSI and 7 from LRI
